#pragma once
#ifndef IMAGEEDITOR_MODULES_FRAMES_TAGS_H
#define IMAGEEDITOR_MODULES_FRAMES_TAGS_H

namespace ImageEditor::Modules
{
    static const char* FILTER_BUTTON_TAG = "FILTER_BUTTON_TAG";
}
#endif //IMAGEEDITOR_MODULES_FRAMES_TAGS_H